### ISSUE TITLE
Generator not working ?

### ISSUE THREAD

**Issue by fredericnowak** [chef-partners/cookbook-guide-generator#7]
Hello, 

I am trying to use this project to bootstrap new cookbooks repo.

Here are the versions of my chef tools:
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3

when I run the command 'chef generate cookbook  -g ...', I have the following error.

Installing Cookbook Gems:
Compiling Cookbooks...
[2017-01-23T16:42:02+01:00] WARN: Cloning resource attributes for template[/Users/fredericnowak/Sources/hydra/alphard-chef-cookbook-seed/alphard-chef-cookbook-seed/.travis.yml] from prior resource (CHEF-3694)
[2017-01-23T16:42:02+01:00] WARN: Previous template[/Users/fredericnowak/Sources/hydra/alphard-chef-cookbook-seed/alphard-chef-cookbook-seed/.travis.yml]: /tmp/cookbook-guide-generator/cookbooks/code_generator/recipes/cookbook.rb:66:in `from_file'
[2017-01-23T16:42:02+01:00] WARN: Current  template[/Users/fredericnowak/Sources/hydra/alphard-chef-cookbook-seed/alphard-chef-cookbook-seed/.travis.yml]: /tmp/cookbook-guide-generator/cookbooks/code_generator/recipes/cookbook.rb:180:in `from_file'

================================================================================
Recipe Compile Error in /tmp/cookbook-guide-generator/cookbooks/code_generator/recipes/cookbook.rb
================================================================================

NoMethodError
-------------
undefined method `enable_delivery' for #<ChefDK::Generator::Context:0x007f96ff811d28>

Cookbook Trace:
---------------
  /tmp/cookbook-guide-generator/cookbooks/code_generator/recipes/cookbook.rb:193:in `from_file'

Relevant File Content:
----------------------
/tmp/cookbook-guide-generator/cookbooks/code_generator/recipes/cookbook.rb:

186:  # kitchen-docker.yml
187:  template "#{cookbook_dir}/.kitchen-docker.yml" do
188:    source 'kitchen.docker.yml.erb'
189:    helpers(ChefDK::Generator::TemplateHelper)
190:    action :create_if_missing
191:  end
192:  
193>> include_recipe 'code_generator::build_cookbook' if context.enable_delivery
194:  

Platform:
---------
x86_64-darwin13.0

ERROR: Chef failed to converge: undefined method `enable_delivery' for #<ChefDK::Generator::Context:0x007f96ff811d28>
Caused by: (NoMethodError) undefined method `enable_delivery' for #<ChefDK::Generator::Context:0x007f96ff811d28>

**Comment by jjasghar** [comment]
Thanks for the report, I'll verify it ASAP.

**Comment by jjasghar** [comment]
Ah!  Please update your ChefDK. 

```
09:59:29 JJs-MacBook-Pro tmp > chef generate cookbook -g ~/repo/cookbook-guide-generator/cookbooks test
Generating cookbook test
WARN: Please configure the generator cookbook by giving the full path to the desired cookbook (like '/Users/jjasghar/repo/cookbook-guide-generator/cookbooks/code_generator')
Recipe: code_generator::cookbook
  * directory[/Users/jjasghar/tmp/test] action create
    - create new directory /Users/jjasghar/tmp/test
  * template[/Users/jjasghar/tmp/test/metadata.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/metadata.rb
    - update content in file /Users/jjasghar/tmp/test/metadata.rb from none to c13eaf
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/README.md] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/README.md
    - update content in file /Users/jjasghar/tmp/test/README.md from none to e0431e
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/TESTING.md] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/TESTING.md
    - update content in file /Users/jjasghar/tmp/test/TESTING.md from none to 0c1ad0
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/Rakefile] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/Rakefile
    - update content in file /Users/jjasghar/tmp/test/Rakefile from none to e80d70
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/LICENSE] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/LICENSE
    - update content in file /Users/jjasghar/tmp/test/LICENSE from none to 8173d5
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.rubocop.yml] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.rubocop.yml
    - update content in file /Users/jjasghar/tmp/test/.rubocop.yml from none to 65faee
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.travis.yml] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.travis.yml
    - update content in file /Users/jjasghar/tmp/test/.travis.yml from none to 998f53
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/CONTRIBUTING.md] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/CONTRIBUTING.md
    - update content in file /Users/jjasghar/tmp/test/CONTRIBUTING.md from none to 2a0b86
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/chefignore] action create
    - create new file /Users/jjasghar/tmp/test/chefignore
    - update content in file /Users/jjasghar/tmp/test/chefignore from none to e394e1
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/Gemfile] action create
    - create new file /Users/jjasghar/tmp/test/Gemfile
    - update content in file /Users/jjasghar/tmp/test/Gemfile from none to af6d44
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/Guardfile] action create
    - create new file /Users/jjasghar/tmp/test/Guardfile
    - update content in file /Users/jjasghar/tmp/test/Guardfile from none to 310e7c
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/Berksfile] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/Berksfile
    - update content in file /Users/jjasghar/tmp/test/Berksfile from none to 5ec92e
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.kitchen.yml] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.kitchen.yml
    - update content in file /Users/jjasghar/tmp/test/.kitchen.yml from none to c6d53b
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/test/integration/default/] action create
    - create new directory /Users/jjasghar/tmp/test/test/integration/default/
  * template[/Users/jjasghar/tmp/test/test/integration/default/default_spec.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/test/integration/default/default_spec.rb
    - update content in file /Users/jjasghar/tmp/test/test/integration/default/default_spec.rb from none to f9f144
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/spec/unit/recipes] action create
    - create new directory /Users/jjasghar/tmp/test/spec/unit/recipes
  * cookbook_file[/Users/jjasghar/tmp/test/spec/spec_helper.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/spec/spec_helper.rb
    - update content in file /Users/jjasghar/tmp/test/spec/spec_helper.rb from none to 6a6973
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/spec/unit/recipes/default_spec.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/spec/unit/recipes/default_spec.rb
    - update content in file /Users/jjasghar/tmp/test/spec/unit/recipes/default_spec.rb from none to 9c9a57
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/recipes] action create
    - create new directory /Users/jjasghar/tmp/test/recipes
  * template[/Users/jjasghar/tmp/test/recipes/default.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/recipes/default.rb
    - update content in file /Users/jjasghar/tmp/test/recipes/default.rb from none to 8c2678
    (diff output suppressed by config)
  * execute[initialize-git] action run
    - execute git init .
  * cookbook_file[/Users/jjasghar/tmp/test/.gitignore] action create
    - create new file /Users/jjasghar/tmp/test/.gitignore
    - update content in file /Users/jjasghar/tmp/test/.gitignore from none to dd37b2
    (diff output suppressed by config)
  * execute[git-add-new-files] action run
    - execute git add .
  * execute[git-commit-new-files] action run
    - execute git commit -m "Add generated cookbook content"
  * template[/Users/jjasghar/tmp/test/.travis.yml] action create_if_missing (up to date)
  * template[/Users/jjasghar/tmp/test/.kitchen-docker.yml] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.kitchen-docker.yml
    - update content in file /Users/jjasghar/tmp/test/.kitchen-docker.yml from none to dd5e71
    (diff output suppressed by config)
Recipe: code_generator::build_cookbook
  * directory[/Users/jjasghar/tmp/test/.delivery] action create
    - create new directory /Users/jjasghar/tmp/test/.delivery
  * cookbook_file[/Users/jjasghar/tmp/test/.delivery/config.json] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/config.json
    - update content in file /Users/jjasghar/tmp/test/.delivery/config.json from none to f1cb30
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/.delivery/build-cookbook] action create
    - create new directory /Users/jjasghar/tmp/test/.delivery/build-cookbook
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/metadata.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/metadata.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/metadata.rb from none to dc1862
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/README.md] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/README.md
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/README.md from none to e6bbd8
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/LICENSE] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/LICENSE
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/LICENSE from none to 8173d5
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/chefignore] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/chefignore
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/chefignore from none to e394e1
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/Berksfile] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/Berksfile
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/Berksfile from none to 718e94
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes] action create
    - create new directory /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/default.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/default.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/default.rb from none to 170a74
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/deploy.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/deploy.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/deploy.rb from none to c75caa
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/functional.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/functional.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/functional.rb from none to ea8429
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/lint.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/lint.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/lint.rb from none to c6c953
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/provision.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/provision.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/provision.rb from none to 964cb3
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/publish.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/publish.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/publish.rb from none to 46b638
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/quality.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/quality.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/quality.rb from none to 81108d
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/security.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/security.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/security.rb from none to 2d9eac
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/smoke.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/smoke.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/smoke.rb from none to 7deca2
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/syntax.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/syntax.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/syntax.rb from none to c44d9a
    (diff output suppressed by config)
  * template[/Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/unit.rb] action create_if_missing
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/unit.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/recipes/unit.rb from none to a5108e
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/.kitchen.yml] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/.kitchen.yml
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/.kitchen.yml from none to 084d67
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/.delivery/build-cookbook/data_bags/keys] action create
    - create new directory /Users/jjasghar/tmp/test/.delivery/build-cookbook/data_bags/keys
  * file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/data_bags/keys/delivery_builder_keys.json] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/data_bags/keys/delivery_builder_keys.json
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/data_bags/keys/delivery_builder_keys.json from none to eedd06
    (diff output suppressed by config)
  * directory[/Users/jjasghar/tmp/test/.delivery/build-cookbook/secrets] action create
    - create new directory /Users/jjasghar/tmp/test/.delivery/build-cookbook/secrets
  * file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/secrets/fakey-mcfakerton] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/secrets/fakey-mcfakerton
  * directory[/Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/recipes] action create
    - create new directory /Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/recipes
  * file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/metadata.rb] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/metadata.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/metadata.rb from none to 2a9650
    (diff output suppressed by config)
  * cookbook_file[/Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/recipes/default.rb] action create
    - create new file /Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/recipes/default.rb
    - update content in file /Users/jjasghar/tmp/test/.delivery/build-cookbook/test/fixtures/cookbooks/test/recipes/default.rb from none to 28715b
    (diff output suppressed by config)
  * execute[git-create-feature-branch] action run
    - execute git checkout -t -b add-delivery-configuration
  * execute[git-add-delivery-config-json] action run
    - execute git add .delivery/config.json
  * execute[git-commit-delivery-config] action run
    - execute git commit -m "Add generated delivery configuration"
  * execute[git-add-delivery-build-cookbook-files] action run
    - execute git add .delivery
  * execute[git-commit-delivery-build-cookbook] action run
    - execute git commit -m "Add generated delivery build cookbook"
  * execute[git-return-to-master-branch] action run
    - execute git checkout master
  * execute[git-merge-delivery-config-branch] action run
    - execute git merge --no-ff add-delivery-configuration
  * execute[git-remove-delivery-config-branch] action run
    - execute git branch -d add-delivery-configuration

Your cookbook is ready. To setup the pipeline, type `cd test`, then run `delivery init`
09:59:43 JJs-MacBook-Pro tmp >
```

**Comment by jjasghar** [comment]
Please reopen this issue with an error after updating your ChefDK. 🤘
